platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: docker-tcpbouncer

outputs:
  - name: image-params

run:
  path: ./docker-tcpbouncer/.ci/build.sh
